#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHONPATH="${SCRIPT_DIR}/src:${SCRIPT_DIR}${PYTHONPATH:+:${PYTHONPATH}}" \
OPEN_WORKSHOP_MANAGER_HOST="${OPEN_WORKSHOP_MANAGER_HOST:-0.0.0.0}" \
OPEN_WORKSHOP_MANAGER_PORT="${OPEN_WORKSHOP_MANAGER_PORT:-7776}" \
OPEN_WORKSHOP_MANAGER_WORKERS="${OPEN_WORKSHOP_MANAGER_WORKERS:-2}" \
exec python -m open_workshop_manager
